name: CI - Lint Leetcode Directory

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint on leetcode directory
        run: |
          pylint leetcode/ --fail-under=8.0 --disable=invalid-name,too-few-public-methods
        continue-on-error: false
